---
extends: default

ignore: |
  archive/

rules:
  braces:
    max-spaces-inside: 1
  comments:
    min-spaces-from-content: 1
  document-start:
    present: true
  line-length:
    max: 120
    level: warning
  truthy:
    allowed-values:
      - "true"
      - "false"
    check-keys: false
